In [ ]:
import pandas as pd
import numpy as np

# Now we will import the data

In [445]:
movie_df = pd.read_csv('/content/tmdb_5000_movies.csv')
credit_df = pd.read_csv('/content/tmdb_5000_credits.csv')

/tmp/ipykernel_700/2433874212.py:2: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264) have mixed types. Specify dtype option on import or set low_memory=False.
  credit_df = pd.read_csv('/content/tmdb_5000_credits.csv')

In [283]:
movie_df.shape

(4803, 20)

In [284]:
movie_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [423]:
movie_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [446]:
credit_df.head(1)

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#We have got a corrupt data here

In [476]:
credit_df.shape

(4812, 3)

In [436]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Columns: 1265 entries, movie_id to Unnamed: 1264
dtypes: object(1265)
memory usage: 46.4+ MB

In [538]:
credit_df = credit_df[["movie_id","title","cast"]]

In [539]:
credit_df.shape

(4812, 3)

In [ ]:
credit_df.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [542]:
df = movie_df.merge(credit_df, on ="title")

In [529]:
df.shape

(4807, 22)

In [543]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4807 entries, 0 to 4806
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4807 non-null   int64
 1   genres                4807 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4807 non-null   int64
 4   keywords              4807 non-null   object
 5   original_language     4807 non-null   object
 6   original_title        4807 non-null   object
 7   overview              4804 non-null   object
 8   popularity            4807 non-null   float64
 9   production_companies  4807 non-null   object
 10  production_countries  4807 non-null   object
 11  release_date          4806 non-null   object
 12  revenue               4807 non-null   int64
 13  runtime               4805 non-null   float64
 14  spoken_languages      4807 non-null   object
 15  status                4807 non-null   object
 16  tagline               3964 non-null   object
 17  title                 4807 non-null   object
 18  vote_average          4807 non-null   float64
 19  vote_count            4807 non-null   int64
 20  movie_id              4807 non-null   object
 21  cast                  4807 non-null   object
dtypes: float64(3), int64(4), object(15)
memory usage: 826.3+ KB

In [544]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast'],
      dtype='object')

In [481]:
(df["original_title"] == df["title"]).sum()

np.int64(4545)

Now we will decide which all columns are important to develop a recommendation system

Relevant columns are \
id \
genres \
keywords \
overview \
title \
cast \
crew

In [545]:
df = df[["movie_id", "title","overview","genres","keywords","cast"]]
df.head(2)

,movie_id,title,overview,genres,keywords,cast
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa..."

In [483]:
#Lets check missing data
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
dtype: int64

In [547]:
#Since there are only three 3 overviews as empty, hence we will drop it.
df.dropna(inplace = True)

In [548]:
#Lets check missing data
df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
dtype: int64

In [549]:
#Lets check the duplicated column
df.duplicated().sum()

np.int64(0)

In [461]:
for i in df["genres"]:
    print(i.name)

AttributeError: 'str' object has no attribute 'name'

In [487]:
# The above error is coming because it is not a list but a string. So will have to convert it into a list now.
import ast

In [533]:
def process(obj):
    Lt = []
    for i in ast.literal_eval(obj):
        Lt.append(i["name"])
    return Lt

In [550]:
df["genres"] = df["genres"].apply(process)

In [295]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [551]:
df["keywords"] = df["keywords"].apply(process)

In [297]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
#Example of a cast list
for i in ast.literal_eval(df["cast"][0]):
    print(i)
    pass

In [664]:
def process2(obj):
    Lt = []
    j = 0
    for i in ast.literal_eval(obj):
        Lt.append(i["name"])
        j+=1
        if j == 3:
            break
    return Lt

In [553]:
df["cast"] = df["cast"].apply(process2)

SyntaxError: unterminated string literal (detected at line 1) (<unknown>, line 1)

The above error is because of error in database and hence will have to delete the cast column from the dataFrame.

In [554]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa..."

In [555]:
df = df[["movie_id","title","overview","genres","keywords"]]

In [666]:
def conversion_type(obj):
    Lt = []
    Lt.append(ast.literal_eval(obj))
    return Lt

In [375]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [400]:
Ls = []
for i in range(28):
    Lst.append(fetch_director(df["crew"][i]))
print(Ls)

[['James Cameron'], ['Gore Verbinski'], ['Sam Mendes'], ['Christopher Nolan'], ['Andrew Stanton'], ['Sam Raimi'], ['Byron Howard', 'Nathan Greno'], ['Joss Whedon'], ['David Yates'], ['Zack Snyder'], ['Bryan Singer'], ['Marc Forster'], ['Gore Verbinski'], ['Gore Verbinski'], ['Zack Snyder'], ['Andrew Adamson'], ['Joss Whedon'], ['Rob Marshall'], ['Barry Sonnenfeld'], ['Peter Jackson'], ['Marc Webb'], ['Ridley Scott'], ['Peter Jackson'], ['Chris Weitz'], ['Peter Jackson'], ['James Cameron'], ['Anthony Russo', 'Joe Russo'], ['Peter Berg']]

In [422]:
fetch_director(df["crew"][28])

SyntaxError: unterminated string literal (detected at line 1) (<unknown>, line 1)

# BECAUSE OF THE CORRUPT DATA IN CREDIT FILE, WE WILL HAVE TO DROP THE DIRECTOR NAME FROM THE CONSIDERATION

In [556]:
df.head()

,movie_id,title,overview,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [557]:
# convert overwiew into a list
df["overview"] = df["overview"].apply(lambda x:x.split())

In [500]:
df.head()

,movie_id,title,overview,genres,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [558]:
# Now it is important to remove space between words in a list
df["genres"] = df["genres"].apply(lambda x:[i.replace(" ","") for i in x])
df["keywords"] = df["genres"].apply(lambda x:[i.replace(" ","") for i in x])

In [506]:
df.head(2)

,movie_id,title,overview,genres,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[Action, Adventure, Fantasy, ScienceFiction]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[Adventure, Fantasy, Action]"

In [559]:
df["tag"] = df["overview"] + df["genres"] + df["keywords"]

In [560]:
new_df = df[["movie_id","title","tag"]]

In [561]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [562]:
new_df["tag"] = new_df["tag"].apply(lambda x:" ".join(x))

/tmp/ipykernel_700/777377641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = new_df["tag"].apply(lambda x:" ".join(x))

In [603]:
new_df.head(3)

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century , a paraplegic marine be d..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believe to be dead , h..."
2,206647,Spectre,a cryptic message from bond ’s past send he on...

In [523]:
new_df["tag"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction Action Adventure Fantasy ScienceFiction'

## Now i will apply Stemming in the tag columns in new_df

In [623]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
ps = PorterStemmer()

In [667]:
def stemming(text):
    Lt = []
    for i in text.split():
        Lt.append(ps.stem(i))
    return " ".join(Lt)

In [627]:
new_df["tag"] = new_df["tag"].apply(stemming)

/tmp/ipykernel_700/2980798421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = new_df["tag"].apply(stemming)

In [629]:
new_df["tag"][0]

'in the 22nd centuri , a parapleg marin be dispatch to the moon pandora on a uniqu mission , but becom tear between follow order and protect an alien civil . action adventur fantasi sciencefict action adventur fantasi sciencefict'

In [630]:
#Lets convert into lower case
new_df["tag"] = new_df["tag"].apply(lambda x:x.lower())

/tmp/ipykernel_700/719539381.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tag"] = new_df["tag"].apply(lambda x:x.lower())

In [631]:
new_df.head(2)

,movie_id,title,tag
0,19995,Avatar,"in the 22nd centuri , a parapleg marin be disp..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believ to be dead , ha..."

In [599]:
#Now we will do vectoization of tags

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3000, stop_words = "english")
# I am choosing less number of maximum features to avoid sparse matrix

In [632]:
tag_vectors = cv.fit_transform(new_df["tag"]).toarray()

In [633]:
tag_vectors.shape

(4804, 3000)

In [714]:
#Following are the most common words in the corpus
j = 0
for i in cv.get_feature_names_out():
    print(i)
    j+=1
    if j == 20:
        break

000
007
10
100
11
12
13
14
15
16
17
18
18th
19
1920
1930
1940
1950
1960
1970

In [635]:
#Now we will utilise cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(tag_vectors)

In [636]:
similarity.shape

(4804, 4804)

In [637]:
similarity

array([[1.        , 0.44566881, 0.25860327, ..., 0.02377585, 0.        ,
        0.        ],
       [0.44566881, 1.        , 0.27852425, ..., 0.05121475, 0.        ,
        0.        ],
       [0.25860327, 0.27852425, 1.        , ..., 0.06686508, 0.02624319,
        0.        ],
       ...,
       [0.02377585, 0.05121475, 0.06686508, ..., 1.        , 0.07720914,
        0.02104913],
       [0.        , 0.        , 0.02624319, ..., 0.07720914, 1.        ,
        0.09913632],
       [0.        , 0.        , 0.        , ..., 0.02104913, 0.09913632,
        1.        ]])

In [ ]:
#Enumerate function to add a counter to a iterable
# Lambda x:x[1] to ensure that sorting occurs based on vector value and not index value

name = "Gandhi"
index = new_df[new_df["title"]==name].index[0]
sorted(enumerate(similarity[index]), reverse=True, key = lambda x:x[1])
#sorted(enumerate(similarity[index]), reverse = True, key = lambda:x:x[1])

The above list shows the index of the movie which are closest to movie Gandhi in decreasing order. Now we just have to convert it into a function to accept any movie

In [705]:
# Final recommendation function
def recom(movie):
    index = new_df[new_df["title"]==movie].index[0]
    distances = sorted(enumerate(similarity[index]), reverse=True, key = lambda x:x[1])
    for i in distances[1:11]:
        print(new_df.iloc[i[0]].title)

In [706]:
recom("Pirates of the Caribbean: On Stranger Tides")

Pirates of the Caribbean: Dead Man's Chest
Krull
Dungeons & Dragons: Wrath of the Dragon God
Highlander
The 13th Warrior
The Hobbit: An Unexpected Journey
Pirates of the Caribbean: The Curse of the Black Pearl
The Legend of Tarzan
The Wolverine
The Scorpion King

In [707]:
recom("Superman Returns")

The Wolverine
Superman II
Superman
Star Wars: Episode I - The Phantom Menace
X-Men: Days of Future Past
Krull
Dungeons & Dragons: Wrath of the Dragon God
Superman III
Journey 2: The Mysterious Island
Underworld: Rise of the Lycans

In [708]:
recom("Green Lantern")

X-Men: The Last Stand
Dragonball Evolution
Jupiter Ascending
The Abyss
Insurgent
G.I. Joe: Retaliation
Fantastic 4: Rise of the Silver Surfer
The Fifth Element
The Covenant
The Matrix Revolutions